source "https://rubygems.org"

gem "jekyll", "~> 3.8.5"
  
group :jekyll_plugins do
  gem "jekyll-avatar"
  gem "jekyll-feed"
  gem "jekyll-github-metadata"
  gem "jekyll-liquify"
  gem "jekyll-mentions"
  gem "jekyll-sitemap"
  gem "jemoji"
end

group :development do
  # Environment context
  gem "dotenv"
  
  # Image optimization
  gem "image_optim"
  gem "image_optim_pack"
  gem "jekyll-compress-images"

  # Performance-booster for watching directories on Windows
  gem "wdm", "~> 0.1.0" if Gem.win_platform?

  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem "tzinfo-data" if Gem.win_platform?
end
